<?xml version="1.0" ?>
<!DOCTYPE usuarios_usuario [
  <!ELEMENT usuarios_usuario (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (id?,nome?,data_nascimento?,login?,senha?)+>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT nome (#PCDATA)>
  <!ELEMENT data_nascimento (#PCDATA)>
  <!ELEMENT login (#PCDATA)>
  <!ELEMENT senha (#PCDATA)>
]>
<usuarios_usuario>
  <DATA_RECORD>
    <id>1</id>
    <nome>Luciana Lima</nome>
    <data_nascimento>1994-09-02</data_nascimento>
    <login>luciana_lima</login>
    <senha>iiee32</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>3</id>
    <nome>Luana Adelaide</nome>
    <data_nascimento>1964-09-08</data_nascimento>
    <login>luana_ad</login>
    <senha>123456</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>4</id>
    <nome>Camila Lima de Moraes</nome>
    <data_nascimento>1998-09-16</data_nascimento>
    <login>cami_moraes</login>
    <senha>456789</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>5</id>
    <nome>Rosangela Pereira</nome>
    <data_nascimento>1989-10-05</data_nascimento>
    <login>rosapereira</login>
    <senha>123568</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>6</id>
    <nome>João dos Santos Silva</nome>
    <data_nascimento>2011-10-10</data_nascimento>
    <login>joao_santos</login>
    <senha>joao@gmail.com</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>7</id>
    <nome>João dos Santos Silva</nome>
    <data_nascimento>2011-10-10</data_nascimento>
    <login>joao_santos</login>
    <senha>joao@gmail.com</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>8</id>
    <nome>Carolina Diaz</nome>
    <data_nascimento>1970-08-05</data_nascimento>
    <login>carol_diaz</login>
    <senha>maravilha123</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>9</id>
    <nome>José Lopes</nome>
    <data_nascimento>1985-05-10</data_nascimento>
    <login>jose_lopes</login>
    <senha>124578</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>10</id>
    <nome>Otavio Miranda</nome>
    <data_nascimento>1997-08-05</data_nascimento>
    <login>otavio_miranda</login>
    <senha>minhasenha123</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>11</id>
    <nome>Felipe Dechamps</nome>
    <data_nascimento>1978-08-01</data_nascimento>
    <login>felipe_dechamps</login>
    <senha>dechamps123</senha>
  </DATA_RECORD>
</usuarios_usuario>
